server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: psymanager
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    type: org.postgresql.jdbc2.optional.SimpleDataSource

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_WEB_CLIENT_ID}
            client-secret: ${GOOGLE_WEB_CLIENT_SECRET}
            scope:
              - email
              - profile
          google-mobile:
            provider: google
            client-id: ${GOOGLE_MOBILE_CLIENT_ID}
            client-secret: ${GOOGLE_MOBILE_CLIENT_SECRET}
            scope:
              - email
              - profile

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}

# Twilio Configuration
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  whatsapp-from: ${TWILIO_WHATSAPP_FROM}
  template-sids:
    appointment-confirmation: ${TWILIO_TEMPLATE_CONFIRMATION}
    appointment-rejection: ${TWILIO_TEMPLATE_REJECTION}
    appointment-reminder: ${TWILIO_TEMPLATE_REMINDER}